# composeファイルのバージョン指定
# Doc: https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"

services:
  # サービス(= コンテナ)
  db:
    image: mysql:8.0
    # mysql 8.0から必要になった
    command: --default-authentication-plugin=mysql_native_password
    #コンテナー削除してもmysqlのデータを引き継げる
    volumes:
      - ./api/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4308:3306"  #Sequel ProでDBを確認する為、4306としておく

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./api:/$WORKDIR"
    ports:
      - "3000:3000"
    environment:
      API_DOMAIN: "localhost:$FRONT_PORT"
      BASE_URL: "http://localhost:$API_PORT"
    depends_on:
      - db
  
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./api/openapi.yaml:/openapi.yaml

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$API_PORT"
    # コンテナで実行したいコマンド(CMD)
    command: sh -c "npm install && npm run start"
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api
